---
title: '1031'
author: "chanwoo"
date: '2019 10 31 '
output: html_document
---

# 개요
- 소지역 코드 군집화  
-- 많은 집단의 소지역 코드를 공통된 특성으로 분류하여 집단 수를 줄이자

```{r 세팅, include=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)
library(DT)
library(scales)
library(caret)
options(scipen = 100)

load("../RData/data.sales.time.RData")
```


# 데이터 
```{r 데이터 추출}
# 서울 데이터만
data.sales.time_seoul<- data.sales.time %>% filter(str_sub(BLOCK_CD, 1, 2) == 11) 
# 매출 변수 다 불러오기
time_vari <- c(paste0("SALE_AMT_", sprintf("%02d",seq(0,23)), "TMST"))

data.sales.time_seoul.saleAMT <- data.sales.time_seoul %>% filter(STD_YM == 201601) %>% select(time_vari) 

kmeans(data.sales.time_seoul.saleAMT, 6)  
```
무식하게 변수 다 넣었더니 역시 클러스터링이 잘 안 된다.

```{r 유효한 변수는 무엇일까?}
nzvIdx <- nearZeroVar(data.sales.time_seoul.saleAMT) # 정보량이 0인 변수 제거
nzvIdx # 새벽 1 ~ 8시 제거
data.sales.time_seoul.saleAMT
data.sales.time_seoul.saleAMT[, nzvIdx]
data.sales.time_seoul.saleAMT <- data.sales.time_seoul.saleAMT[, -nzvIdx]


data.sales.time_seoul.saleAMT %>% kmeans(3)


# 변수간에 높은 상관관계 제거
highCorIdx <- data.sales.time_seoul.saleAMT %>% cor %>% findCorrelation(cutoff = 0.7)
highCorIdx
data.sales.time_seoul.saleAMT <- data.sales.time_seoul.saleAMT[,-highCorIdx]

data.sales.time_seoul.saleAMT %>% kmeans(3)
```
계산을 이용해서 유용한 변수를 찾는데 한계가 있다.  직접 수동으로 찾아보자


```{r}

```

