---
title: "0922"
author: "chanwoo"
date: '2019 9 22 '
output: html_document
---

# 데이터 읽기
```{r}
library(dplyr)
library(plyr)
library(tidyr)
library(ggplot2)

a <- read.csv("../data_table/매출/성연령/SALES_AGE_201603.CSV",sep = "|")

head(a)
```
테이블이 "|"로 구분되어 있으며, 
테이블이 각각 홀수 달로 저장되어 있다. 
이를 2016년 데이터 하나로 합치자

# 테이블 홀수 달 합치기
```{r}

readData <- function(app.name, app.name2, subfile.name){
  data <- data.frame()
  dates <- c("201601", "201603", "201605", "201607", "201609", "201611") # 홀수 달
  
  for (date in dates){
    file.name <- sprintf("../data_table/%s/%s/%s", app.name, app.name2, paste0(subfile.name, date, ".CSV")) # 파일 경로
    print(file.name)
    x <- read.csv(file.name, sep = "|")
    data <- rbind(data, x)
  }
  return(data)
}

data.sales.age <- readData("매출", "성연령", "SALES_AGE_")
data.sales.time <- readData("매출", "시간대", "SALES_TIME_")
data.sales.wkdy <- readData("매출", "요일별", "SALES_WKDY_")
data.flow.age <- readData("유동인구", "성연령", "FLOW_AGE_")
data.flow.time <- readData("유동인구", "시간대", "FLOW_TIME_")
data.flow.wkdy <- readData("유동인구", "요일별", "FLOW_WKDY_")


save(data.sales.age, data.sales.time, data.sales.wkdy, 
     data.flow.age, data.flow.time, data.flow.wkdy, file = "data.all.RData")
```

